/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * cusmtreg.java
 *
 * Created on Sep 2, 2010, 9:35:57 AM
 */

package vehiclerentalsystem;

import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author chana911
 */
public class cusmtreg extends javax.swing.JFrame {

    /** Creates new form cusmtreg */
    public cusmtreg() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cusname1 = new javax.swing.JLabel();
        cus_nic1 = new javax.swing.JLabel();
        cusadd1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        phone1 = new javax.swing.JLabel();
        cusnam = new javax.swing.JTextField();
        cusnic = new javax.swing.JTextField();
        cusadd = new javax.swing.JTextField();
        cusphone = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        back = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        rentinterface = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cusname1.setFont(new java.awt.Font("Times New Roman", 0, 24));
        cusname1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cusname1.setText("Customer Name");

        cus_nic1.setFont(new java.awt.Font("Times New Roman", 0, 24));
        cus_nic1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cus_nic1.setText("Customer NIC/PassportNo");

        cusadd1.setFont(new java.awt.Font("Times New Roman", 0, 24));
        cusadd1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cusadd1.setText("Address");

        jLabel4.setFont(new java.awt.Font("Forte", 1, 36));
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("Add Customer ");

        phone1.setFont(new java.awt.Font("Times New Roman", 0, 24));
        phone1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        phone1.setText("Phone");

        cusnam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusnamActionPerformed(evt);
            }
        });

        add.setFont(new java.awt.Font("Forte", 0, 18)); // NOI18N
        add.setForeground(new java.awt.Color(0, 0, 102));
        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        back.setFont(new java.awt.Font("Forte", 0, 18));
        back.setForeground(new java.awt.Color(0, 0, 102));
        back.setText("Main");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        Clear.setFont(new java.awt.Font("Forte", 0, 18));
        Clear.setForeground(new java.awt.Color(0, 0, 102));
        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        rentinterface.setFont(new java.awt.Font("Forte", 0, 18));
        rentinterface.setForeground(new java.awt.Color(0, 0, 102));
        rentinterface.setText("Rent Details");
        rentinterface.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentinterfaceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 832, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cusname1)
                            .addComponent(cus_nic1))
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cusnam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(cusnic, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(cusadd, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(cusphone, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                        .addGap(338, 338, 338))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rentinterface)
                        .addGap(18, 18, 18)
                        .addComponent(back))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cusadd1)
                            .addComponent(phone1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 756, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cusname1)
                    .addComponent(cusnam, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(cusnic, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cus_nic1)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cusadd1)
                    .addComponent(cusadd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phone1)
                    .addComponent(cusphone, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back)
                    .addComponent(rentinterface)
                    .addComponent(Clear)
                    .addComponent(add))
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        new main1().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_backActionPerformed

    private void clear(){
        cusnam.setText("");
        cusnic.setText("");
        cusadd.setText("");
        cusphone.setText("");
        cusnam.requestFocus();
    }
    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        // TODO add your handling code here:
        
        cusnam.setText("");
        cusnic.setText("");
        cusadd.setText("");
        cusphone.setText("");
        cusnam.requestFocus();

}//GEN-LAST:event_ClearActionPerformed

    private void cusnamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusnamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cusnamActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        try {
            // TODO add your handling code here:
            Connection conn = myconn1.getConnection();
            Statement s = conn.createStatement();
            s.executeUpdate(" insert into customer (cusNic_pass,cusname,address,phone) values ('" + cusnic.getText() + "' , '" + cusnam.getText() + "','" + cusadd.getText() + "','" + cusphone.getText() + "')");
            JOptionPane.showMessageDialog(null, "Record Succesfully inserted");

            clear();
        }
        catch (Exception ex) {
            //Logger.getLogger(cusmtreg.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Record insert failed");
        }
    }//GEN-LAST:event_addActionPerformed

    private void rentinterfaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentinterfaceActionPerformed
        // TODO add your handling code here:
        new rentalsystem().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rentinterfaceActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cusmtreg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JButton add;
    private javax.swing.JButton back;
    private javax.swing.JLabel cus_nic1;
    private javax.swing.JTextField cusadd;
    private javax.swing.JLabel cusadd1;
    private javax.swing.JTextField cusnam;
    private javax.swing.JLabel cusname1;
    private javax.swing.JTextField cusnic;
    private javax.swing.JTextField cusphone;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel phone1;
    private javax.swing.JButton rentinterface;
    // End of variables declaration//GEN-END:variables

}
