/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * rentalsystem.java
 *
 * Created on Sep 2, 2010, 9:39:07 AM
 */

package vehiclerentalsystem;

import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
/**
 *
 * @author chana911
 */
public class rentalsystem extends javax.swing.JFrame {

    /** Creates new form rentalsystem */
    public rentalsystem() {
        initComponents();
        loadcusno();
        loadvhno();
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cusnic = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        regCustomer = new javax.swing.JButton();
        cusno = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        deposite = new javax.swing.JTextField();
        hiredate = new javax.swing.JTextField();
        hirerate = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        nopassenger = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        nodays = new javax.swing.JTextField();
        returndate = new javax.swing.JTextField();
        vhid = new javax.swing.JComboBox();
        Clear = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        rentno = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        vhmodel = new javax.swing.JTextField();
        jCalendarButton1 = new net.sourceforge.jcalendarbutton.JCalendarButton();
        jCalendarButton2 = new net.sourceforge.jcalendarbutton.JCalendarButton();
        cusna = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        vhno = new javax.swing.JTextField();
        cusname = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel4.setFont(new java.awt.Font("Forte", 1, 36));
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("Add Rent details ");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 20));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Customer No");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 20));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Vehicle Model");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 20));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Vehicle ID");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 20));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Customer NIC/PassportNo");

        back.setFont(new java.awt.Font("Forte", 0, 18));
        back.setForeground(new java.awt.Color(0, 0, 102));
        back.setText("Main");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        regCustomer.setFont(new java.awt.Font("Forte", 0, 18));
        regCustomer.setForeground(new java.awt.Color(0, 0, 102));
        regCustomer.setText("Register Customer");
        regCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regCustomerActionPerformed(evt);
            }
        });

        cusno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusnoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 20));
        jLabel6.setText("Deposite");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 20));
        jLabel7.setText("Return Date");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 20));
        jLabel8.setText("Hire Date");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 20));
        jLabel9.setText("Hire Rate");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 20));
        jLabel10.setText("No-Passengers");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 20));
        jLabel11.setText("No-Days");

        vhid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vhidActionPerformed(evt);
            }
        });

        Clear.setFont(new java.awt.Font("Forte", 0, 18));
        Clear.setForeground(new java.awt.Color(0, 0, 102));
        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 20));
        jLabel12.setText("Rent-No");

        jButton1.setFont(new java.awt.Font("Forte", 0, 18));
        jButton1.setForeground(new java.awt.Color(0, 0, 102));
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jCalendarButton1.setFocusCycleRoot(true);

        jCalendarButton1.setName("jCalendarButton1"); // NOI18N
        jCalendarButton1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateOnlyPopupChanged(evt);
            }
        });

        jCalendarButton2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                datePopupChanged(evt);
            }
        });

        cusna.setFont(new java.awt.Font("Times New Roman", 0, 20));
        cusna.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cusna.setText("Customer Name");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 20));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Vehicle No");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(246, 246, 246))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 959, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1)
                                .addComponent(jLabel12)
                                .addComponent(cusna)
                                .addComponent(jLabel3)
                                .addComponent(jLabel14)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11)
                                .addComponent(jLabel7))
                            .addGap(45, 45, 45)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(hirerate, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(deposite, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(hiredate)
                                .addComponent(vhmodel)
                                .addComponent(vhno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                .addComponent(cusname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                .addComponent(rentno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                .addComponent(cusno, javax.swing.GroupLayout.Alignment.LEADING, 0, 250, Short.MAX_VALUE)
                                .addComponent(cusnic, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                .addComponent(vhid, 0, 250, Short.MAX_VALUE)
                                .addComponent(returndate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                .addComponent(nopassenger, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                .addComponent(nodays, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jCalendarButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCalendarButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(74, 74, 74)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(regCustomer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(83, 83, 83))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)
                                .addGap(4, 4, 4)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(rentno, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12))
                                        .addGap(11, 11, 11)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(cusno, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1))
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(cusnic, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(cusna)
                                            .addComponent(cusname, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel3)
                                            .addComponent(vhid, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(133, 133, 133)
                                        .addComponent(regCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(274, 274, 274)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(vhno, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(vhmodel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(deposite, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(hiredate, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jCalendarButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(413, 413, 413)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(hirerate, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(nopassenger, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(nodays, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCalendarButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(returndate, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void loadcusno(){
        try {
            Connection conn = myconn1.getConnection();
            Statement s = conn.createStatement();
            ResultSet rs = s.executeQuery("select cusno from customer");
                 cusno.addItem("void");

           cusno.removeAllItems();
  cusno.configureEditor(cusno.getEditor(), null);

            while (rs.next()) {
                cusno.addItem(rs.getString("cusno"));
            }
            rs = s.executeQuery("select cusname,cusNic_pass from customer where cusno = ' " + cusno.getSelectedItem().toString()+"'");
            while (rs.next()) {
                    cusnic.setText(rs.getString("cusNic_pass"));
                    cusname.setText(rs.getString("cusname"));

            }
                rs = s. executeQuery("Select COUNT(rent_id) from rent");
                int count = 0;
              //
                while (rs.next()){
                     count = rs.getInt(1) + 1;
                }

           String formatted = String.format("%04d", count);
            rentno.setText(formatted);

        } catch (Exception ex) {
           // Logger.getLogger(rentalsystem.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }
}
public void loadvhno(){
        try {
            Connection conn = myconn1.getConnection();
            Statement s = conn.createStatement();
            ResultSet rs = s.executeQuery("select vhid from vehicle");
            while (rs.next()) {
                vhid.addItem(rs.getString("vhid"));
            }
            rs = s.executeQuery("select vhno,vhmodel,hirerate from vehicle where vhid = ' " + vhid.getSelectedItem().toString()+"'");
            while (rs.next()) {
                vhno.setText(rs.getString("vhno"));
                vhmodel.setText(rs.getString("vhmodel"));
                hirerate.setText(rs.getString("hirerate"));
            }
        } catch (Exception ex) {
           // Logger.getLogger(rentalsystem.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }


}
    private void regCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regCustomerActionPerformed
        // TODO add your handling code here:
        new cusmtreg().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_regCustomerActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        new main1().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        // TODO add your handling code here:
       deposite.setText("");
       hiredate.setText("");
       hirerate.setText("");
       nopassenger.setText("");
       nodays.setText("");
       returndate.setText("");
       hiredate.requestFocus();

}//GEN-LAST:event_ClearActionPerformed

    private void cusnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusnoActionPerformed
        try {
            // TODO add your handling code here:
            Connection conn = myconn1.getConnection();
            Statement s = conn.createStatement();
            ResultSet rs = s.executeQuery("select  cusname,cusNic_pass  from customer where cusno = '" + cusno.getSelectedItem().toString() + "'");
            while (rs.next()) {
                cusnic.setText(rs.getString("cusNic_pass"));
                cusname.setText(rs.getString("cusname"));
            }
        } catch (Exception ex) {
           // Logger.getLogger(rentalsystem.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_cusnoActionPerformed

    private void vhidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vhidActionPerformed
        // TODO add your handling code here:
        try{
         Connection conn = myconn1.getConnection();
            Statement s = conn.createStatement();

            ResultSet rs = s.executeQuery("select  vhmodel ,hirerate from vehicle where vhid = '" + vhid.getSelectedItem().toString() + "'");
            while (rs.next()) {
                vhno.setText(rs.getString("vhno"));
                vhmodel.setText(rs.getString("vhmodel"));
                hirerate.setText(rs.getString("hirerate"));
            }
        }
            catch (Exception ex){
                ex.printStackTrace();
            }
    }//GEN-LAST:event_vhidActionPerformed
    private void clear(){
        cusname.setText("");
        cusnic.setText("");
        vhno .setText("");
        vhmodel.setText("");
        hiredate.setText("");
        nopassenger.setText("");
        nodays.setText("");
        deposite.setText("");
        returndate.setText("");
        deposite.requestFocus();
        
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            Connection conn = myconn1.getConnection();
            Statement s = conn.createStatement();
            s.executeUpdate(" insert into rent (rent_no,cusno,vhid,deposite,rentdate,return_date,rental_period,no_of_passengers) values ('" + rentno.getText() + "','" + cusno.getSelectedItem() + "','" +vhid.getSelectedItem()+ "','" + deposite.getText() + "' ,'" + hiredate.getText()+ "','" + returndate.getText() + "' ,'" + nodays.getText() + "','" + nopassenger.getText() + "')");
            JOptionPane.showMessageDialog(null, "Record inserted");
            clear();
        } catch (Exception ex) {
            //Logger.getLogger(rentalsystem.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

      private void dateOnlyPopupChanged(java.beans.PropertyChangeEvent evt) {
        if (evt.getNewValue() instanceof Date)
            setDate((Date)evt.getNewValue());
    }

      private void datePopupChanged(java.beans.PropertyChangeEvent evt) {
        if (evt.getNewValue() instanceof Date)
            setDate1((Date)evt.getNewValue());
    }

     public void setDate(Date date)
    {
        String dateString = "";
        if (date != null)
    		dateString = dateFormat.format(date);
        hiredate.setText(dateString);
        jCalendarButton1.setTargetDate(date);
    }

      public void setDate1(Date date)
    {
        String dateString = "";
        if (date != null)
    		dateString = dateFormat.format(date);
        returndate.setText(dateString);
        jCalendarButton2.setTargetDate(date);
    }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rentalsystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JButton back;
    private javax.swing.JLabel cusna;
    private javax.swing.JTextField cusname;
    private javax.swing.JTextField cusnic;
    private javax.swing.JComboBox cusno;
    private javax.swing.JTextField deposite;
    private javax.swing.JTextField hiredate;
    private javax.swing.JTextField hirerate;
    private javax.swing.JButton jButton1;
    private net.sourceforge.jcalendarbutton.JCalendarButton jCalendarButton1;
    private net.sourceforge.jcalendarbutton.JCalendarButton jCalendarButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField nodays;
    private javax.swing.JTextField nopassenger;
    private javax.swing.JButton regCustomer;
    private javax.swing.JTextField rentno;
    private javax.swing.JTextField returndate;
    private javax.swing.JComboBox vhid;
    private javax.swing.JTextField vhmodel;
    private javax.swing.JTextField vhno;
    // End of variables declaration//GEN-END:variables
public static DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
}
