/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * vehiclereg.java
 *
 * Created on Sep 2, 2010, 9:38:18 AM
 */

package vehiclerentalsystem;

import java.sql.Connection;
import java.sql.Statement;
import java.util.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;


/**
 *
 * @author chana911
 */
public class vehiclereg extends javax.swing.JFrame {

    /** Creates new form vehiclereg */
    public vehiclereg() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        vhno1 = new javax.swing.JLabel();
        vhno = new javax.swing.JTextField();
        vhType1 = new javax.swing.JLabel();
        vhtyp = new javax.swing.JTextField();
        vhmodel1 = new javax.swing.JLabel();
        vhserv1 = new javax.swing.JLabel();
        vhmo = new javax.swing.JTextField();
        hire = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        back = new javax.swing.JButton();
        vhrenew1 = new javax.swing.JLabel();
        vhrenew = new javax.swing.JTextField();
        vhInsr1 = new javax.swing.JLabel();
        vhinsu = new javax.swing.JTextField();
        Clear = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jCalendarButton1 = new net.sourceforge.jcalendarbutton.JCalendarButton();
        jCalendarButton2 = new net.sourceforge.jcalendarbutton.JCalendarButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Forte", 1, 24));
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Add vehicle");

        vhno1.setFont(new java.awt.Font("Times New Roman", 0, 24));
        vhno1.setText("Vehicle No");

        vhType1.setFont(new java.awt.Font("Times New Roman", 0, 24));
        vhType1.setText("Vehicle Type");

        vhmodel1.setFont(new java.awt.Font("Times New Roman", 0, 24));
        vhmodel1.setText("Vehicle Model");

        vhserv1.setFont(new java.awt.Font("Times New Roman", 0, 24));
        vhserv1.setText("Hire rate");

        add.setFont(new java.awt.Font("Forte", 0, 18));
        add.setForeground(new java.awt.Color(0, 0, 102));
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        back.setFont(new java.awt.Font("Forte", 0, 18));
        back.setForeground(new java.awt.Color(0, 0, 102));
        back.setText("Main");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        vhrenew1.setFont(new java.awt.Font("Times New Roman", 0, 24));
        vhrenew1.setText("Revenew Date");

        vhInsr1.setFont(new java.awt.Font("Times New Roman", 0, 24));
        vhInsr1.setText("Insurance Date");

        Clear.setFont(new java.awt.Font("Forte", 0, 18));
        Clear.setForeground(new java.awt.Color(0, 0, 102));
        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Forte", 0, 18));
        jButton1.setForeground(new java.awt.Color(0, 0, 102));
        jButton1.setText("Insurance details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jCalendarButton1.setFocusCycleRoot(true);

        jCalendarButton1.setName("jCalendarButton1"); // NOI18N
        jCalendarButton1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateOnlyPopupChanged(evt);
            }
        });

        jCalendarButton2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                datePopupChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(vhType1)
                                            .addComponent(vhserv1)
                                            .addComponent(vhInsr1)
                                            .addComponent(vhno1)
                                            .addComponent(vhmodel1)
                                            .addComponent(vhrenew1))
                                        .addGap(168, 168, 168)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(vhinsu, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                            .addComponent(vhrenew, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                            .addComponent(hire, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                            .addComponent(vhmo, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                            .addComponent(vhtyp, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                            .addComponent(vhno, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addGap(18, 18, 18)
                                        .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(back))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCalendarButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jCalendarButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(268, 268, 268))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vhno1)
                            .addComponent(vhno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vhType1)
                            .addComponent(vhtyp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vhmodel1)
                            .addComponent(vhmo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vhserv1)
                            .addComponent(hire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vhrenew1)
                            .addComponent(vhrenew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jCalendarButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vhInsr1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jCalendarButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(vhinsu, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back)
                    .addComponent(Clear)
                    .addComponent(add)
                    .addComponent(jButton1))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        new main1().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed
private void clear(){
  vhno.setText("");
        vhtyp.setText("");
        vhmo.setText("");
        hire.setText("");
        vhrenew.setText("");
        vhinsu.setText("");
        vhno.requestFocus();
}
    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        // TODO add your handling code here:
        vhno.setText("");
        vhtyp.setText("");
        vhmo.setText("");
        hire.setText("");
        vhrenew.setText("");
        vhinsu.setText("");
        vhno.requestFocus();
}//GEN-LAST:event_ClearActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        try {
            // TODO add your handling code here:
            Connection conn = myconn1.getConnection();
            Statement s = conn.createStatement();


            s.executeUpdate("insert into vehicle (vhno,vhtype,vhmodel,hirerate,dateofrenewlicence,date_Of_insurance) values ('" + vhno.getText() + "' , '" + vhtyp.getText() + "','"
                             + vhmo.getText() + "' , '" + hire.getText() + "' , '" + vhrenew.getText() + "','" + vhinsu.getText() + "')");
            JOptionPane.showMessageDialog(null, "Record Succesfully inserted");
            clear();

        } catch (Exception ex) {
            //Logger.getLogger(vehiclereg.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Record insert failed");
        }

    }//GEN-LAST:event_addActionPerformed

     private void dateOnlyPopupChanged(java.beans.PropertyChangeEvent evt) {                                      
        if (evt.getNewValue() instanceof Date)
            setDate((Date)evt.getNewValue());
    }

      private void datePopupChanged(java.beans.PropertyChangeEvent evt) {                                      
        if (evt.getNewValue() instanceof Date)
            setDate1((Date)evt.getNewValue());
    }


      /**
     * Validate and set the datetime field on the screen given a datetime string.
     * @param dateTime The datetime string
     */
  

    /**
     * Validate and set the datetime field on the screen given a date.
     * @param dateTime The datetime object
     */
    public void setDate(Date date)
    {
        String dateString = "";
        if (date != null)
    		dateString = dateFormat.format(date);
        vhrenew.setText(dateString);
        jCalendarButton1.setTargetDate(date);
    }

      public void setDate1(Date date)
    {
        String dateString = "";
        if (date != null)
    		dateString = dateFormat.format(date);
        vhinsu.setText(dateString);
        jCalendarButton2.setTargetDate(date);
    }





    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new insurance().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vehiclereg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JButton add;
    private javax.swing.JButton back;
    private javax.swing.JTextField hire;
    private javax.swing.JButton jButton1;
    private net.sourceforge.jcalendarbutton.JCalendarButton jCalendarButton1;
    private net.sourceforge.jcalendarbutton.JCalendarButton jCalendarButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel vhInsr1;
    private javax.swing.JLabel vhType1;
    private javax.swing.JTextField vhinsu;
    private javax.swing.JTextField vhmo;
    private javax.swing.JLabel vhmodel1;
    private javax.swing.JTextField vhno;
    private javax.swing.JLabel vhno1;
    private javax.swing.JTextField vhrenew;
    private javax.swing.JLabel vhrenew1;
    private javax.swing.JLabel vhserv1;
    private javax.swing.JTextField vhtyp;
    // End of variables declaration//GEN-END:variables
public static DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");

}
